package qwert.inte;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.After;
import org.junit.Before;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.time.Duration;
public class DaTest {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
 
 System.setProperty("webdriver.chrome.driver", "C:\\Driver\\chromedriver.exe");
 ChromeOptions options = new ChromeOptions();
 options.addArguments("--remote-allow-origins=*");
 driver = new ChromeDriver(options);
 
 WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
 
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void da() throws InterruptedException {
	String Title,Email,Password,Verifier,Pverifier,error,Login;
	driver.get("https://admin.yelo.red/en/page/login");
    driver.manage().window().maximize();
    Title = driver.getTitle();
    System.out.println("1. Title of the WebPage is " + Title);
    WebElement i = driver.findElement
    	      (By.xpath("/html/body/app-root/app-login/div/div[1]/div[2]/div[1]/div/div[1]/img"));
    Boolean Logo = (Boolean) ((JavascriptExecutor)driver) .executeScript("return arguments[0].complete " + "&& typeof arguments[0].naturalWidth != \"undefined\" " + "&& arguments[0].naturalWidth > 0", i);
    if (Logo) {
        System.out.println("2. Logo present");
     } else {
        System.out.println("2. Logo not present");
     }
    Email = driver.findElement(By.xpath("/html/body/app-root/app-login/div/div[1]/div[2]/div[2]/div/div/div[2]/form/div[1]/input")).getAttribute("placeholder");
    Verifier = "Enter email";
    
    if(Email.equals(Verifier)) {
    	System.out.println("3. Email Container Box exists");
    }
    else
    {
    	System.out.println("3. Email Container box doesn't exists");
    }
    Password = driver.findElement(By.xpath("/html/body/app-root/app-login/div/div[1]/div[2]/div[2]/div/div/div[2]/form/div[2]/input")).getAttribute("placeholder");
    Pverifier = "Enter Password";
    if(Password.equals(Pverifier)) {
    	System.out.println("4. Password Container Box exists");
    }
    else
    {
    	System.out.println("4. Password Container box doesn't exists");
    }
    //Login button testing 
    boolean eleSelected= driver.findElement(By.xpath("/html/body/app-root/app-login/div/div[1]/div[2]/div[2]/div/div/div[2]/form/div[4]/button")).isDisplayed();
    System.out.println("4.1 The Button label : " + eleSelected);
    //Entering the wrong  email id and wrong password 
    driver.findElement(By.id("exampleInputEmail1")).click();
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("testdsaemail@gmail.com");
    driver.findElement(By.id("exampleInputPassword1")).click();
    driver.findElement(By.id("exampleInputPassword1")).sendKeys("Qwerty");
    driver.findElement(By.cssSelector(".custom_register_btn-primary")).click();
    error = driver.findElement(By.xpath("/html/body/app-root/p-toast/div/p-toastitem")).getText();
    // Entering the registered email and wrong password
    System.out.println("5. Error message for wrong Email and Password details " + error);
    driver.findElement(By.id("exampleInputEmail1")).click();
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("multi1@yopmail.com");
    driver.findElement(By.id("exampleInputPassword1")).click();
    driver.findElement(By.id("exampleInputPassword1")).sendKeys("Qwerty123");
    driver.findElement(By.cssSelector(".custom_register_btn-primary")).click();
    error = driver.findElement(By.xpath("/html/body/app-root/p-toast/div/p-toastitem")).getText();
    System.out.println("6. Error message for wrong password details " + error);
    //Buttons testing
     //Forgot Pasword Button
    driver.findElement(By.xpath("/html/body/app-root/app-login/div/div[1]/div[2]/div[2]/div/div/div[2]/form/div[3]/span/a")).click();
    System.out.println(driver.getCurrentUrl());
    driver.navigate().to("https://admin.yelo.red");
    //Login Button
   driver.findElement(By.xpath("/html/body/app-root/app-login/div/div[1]/div[2]/div[2]/div/div/div[2]/form/div[4]/button")).click();
   System.out.println(driver.getCurrentUrl());
   //driver.navigate().to("https://admin.yelo.red");
 //Sign UP Button
   driver.findElement(By.xpath("/html/body/app-root/app-login/div/div[1]/div[2]/div[2]/div/div/div[2]/form/div[5]/p/a")).click();
   System.out.println(driver.getCurrentUrl());
   driver.navigate().to("https://admin.yelo.red");
   //Login Via OTP button
  driver.findElement(By.xpath("/html/body/app-root/app-login/div/div[1]/div[2]/div[2]/div/div/div[3]/p/span")).click();
  System.out.println(driver.getCurrentUrl());
  //Timeouts implicitlyWait = driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
  driver.navigate().to("https://admin.yelo.red");
  //Google Button
  driver.findElement(By.xpath("/html/body/app-root/app-login/div/div[1]/div[2]/div[2]/div/div/div[4]/div/app-google-login/button")).click();
  System.out.println(driver.getCurrentUrl());
}
}
